### ISSUE TITLE
Notebook does not run:  probable problem with `SNPhot_fitter_filt`

### ISSUE THREAD

**Issue by rbiswas4** [djreiss/SNclass#1]
I was trying to run the notebook on the data on my computer (simply changed directory names) and failed : The failure is shown in 

https://github.com/rbiswas4/SNclass/blob/master/SNclass-latest.ipynb
(cell 4 has the failure).

I think this has to do with 
`SNPhot_fitter_filt` but am not sure. You can scroll down to the scratch section at the bottom of the file to see some more output relating to the problem.

**Comment by djreiss** [comment]
Try the latest (dev) version of george:

pip install --user git+git://github.com/dfm/george.git@1.0-dev
